version: '3.1'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    links:
      - elasticsearch
      - prometheus
  elasticsearch:
    image: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
